### ISSUE TITLE
Undefined variable in `iterate.LengFunc`

### ISSUE THREAD

**Issue by ZedThree** [FusionDLS/FusionDLS#27]
`ne` here seems to be undefined:

https://github.com/cydcowley/DLS-model/blob/8f930f5526c09616605d71434be3439fc09ea7db/Iterate.py#L67

**Comment by mikekryjak** [comment]
That line of code is for an implementation of an electron conduction flux limiter which was never finished and has been abandoned for now. My guess is that it's using `ne` because that was the previous convention in Cyd's original version before I started working on the project, and I never touched any of the flux limiter stuff.

The way that the DLS model works now is that the only density that matters for the iteration is the upstream density, and that is set outside of `Iterate` and passed to it. This means there's no need to recalculate `ne` and it should be named `nu`.

To avoid confusion I think that the flux limiter code should be taken out as it's never worked. We could put it into a PR instead. What do you think @cydcowley?
